### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by albulescu** [goioc/di#13]
Is it possible to call PostConstruct first for dependencies?

**Comment by dtitov** [comment]
Hi. It's not trivial. Imagine that bean A is injected into bean B, and bean B is injected into bean A. They are referencing each-other, i.e. are dependencies of each-other. For which of them the PostConstruct should be called first?

Also, maybe you could describe your particular use-case for this? Then I could think of an alternative solution.

**Comment by dtitov** [comment]
Closing this one for now. Feel free to reopen have you any further comments.
