### ISSUE TITLE
Improve beans initialization

### ISSUE THREAD

**Issue by lucas-gio** [goioc/di#17]
**Problem**
When i read the description, is confusing what i have do for get an initialization. The example is not the best in comparison with weather example.

**Solution**
Detail that the mentioned interface has the postConstruct method which must be coded so that it is executed after the creation of the instance.

And, thanks for doing this brilliant job!

**Comment by dtitov** [comment]
Dear Lucas, thanks for the feedback. Have you read this chapter of the readme: https://github.com/goioc/di#beans-initialization ? I can adjust it to make it clearer, do you have any particular suggestions (also, feel free to create a PR, if you like).

**Comment by dtitov** [comment]
I've added another chapter about initialization with bean post-processors. Closing this issue for now. Feel free to reopen.
