### ISSUE TITLE
[Feature request] register&inject bean with named group

### ISSUE THREAD

**Issue by junneyang** [goioc/di#19]
register: ``` func RegisterBeanWithGroup(beanID string, beanGroup string, beanType reflect.Type)     
func RegisterBeanInstance(beanID string, beanGroup string, beanInstance interface{}) ```
inject:     ``` HandlerList []Handler `group:"server,flatten"` ```

reference: https://pkg.go.dev/go.uber.org/dig#hdr-Value_Groups

we think this feature is very useful, thanks !

**Comment by dtitov** [comment]
Hi,

Thanks for your interest in the project. Can you describe some example use-case for this? I'm trying to keep this lib as simple as possible, and at the first glance it looks like something to be used quite seldom... But perhaps I would be able to suggest some alternative solutions 🙂

**Comment by junneyang** [comment]
our case:

**Comment by junneyang** [comment]
![image](https://user-images.githubusercontent.com/6802322/133082437-f9619e1d-190c-473c-ae72-f6739be6d991.png)

we have a pluginable application, suppose ConfigService is pluginable,
we implement the default: DefaultUserConfigService, DefaultResourceConfigService, DefaultPermissionConfigService
and some external extends the custom: CustomUserConfigService, CustomResourceConfigService, CustomPermissionConfigService


we want this result:
beans := di.getBeanByGroup(${group})
for bean := range beans {
    bean.config()
}

group could be "default" or "custom"

**Comment by dtitov** [comment]
You can inject collection of beans by type. Check this out:

```golang
type SomeBean struct {
	configServices []*ConfigService `di.inject:""`
}
```

All beans that implement/extend `ConfigService` type will be injected here. Note that you have to leave `di.inject` empty.

I hope this helps :)

**Comment by junneyang** [comment]
> You can inject a collection of beans by type. Check this out:
> 
> ```go
> type SomeBean struct {
> 	configServices []ConfigService `di.inject:""`
> }
> ```
> 
> All beans that implement `ConfigService` type will be injected here (assuming it's an interface). Note that you have to leave `di.inject` empty.
> 
> I hope this helps :)

yes, i know about this feature of di,
but how can i get the only default or custom 3 configServices ?

**Comment by dtitov** [comment]
Oh, I see, you need only one of these groups, not all of them. Well, in this case I see two options: add a method called that returns a type of your config service, e.g.
```golang
func (cs DefaultUserConfigService) IsDefault() bool {
	return true
}
...
func (cs CustomUserConfigService) IsDefault() bool {
	return false
}
```

And then in your range loop filter by this method.

Or you could introduce intermediate interfaces, like, `DefaultConfigService` and `CustomConfigService` and then inject by this interface (instead of parent interface `ConfigService`).

**Comment by junneyang** [comment]
> Oh, I see, you need only one of these groups, not all of them. Well, in this case I see two options: add a method that returns a type of your config service, e.g.
> 
> ```go
> func (cs *DefaultUserConfigService) IsDefault() bool {
> 	return true
> }
> ...
> func (cs *CustomUserConfigService) IsDefault() bool {
> 	return false
> }
> ```
> 
> And then in your range loop filter by this method.
> 
> Or you could introduce intermediate interfaces, like, `DefaultConfigService` and `CustomConfigService` and then inject by this interfaces (instead of parent interface `ConfigService`).

thanks very much, the first option fits well !
