### ISSUE TITLE
[Feature request] when the Prototype bean destroy?

### ISSUE THREAD

**Issue by junneyang** [goioc/di#20]

**Comment by dtitov** [comment]
Prototype beans are not getting destroyed automatically (neither are singletones). Only request-scoped beans have a specific lifecycle, which is bound to a web-request. However, you can shut down the whole container with method `Close()`: https://github.com/goioc/di/blob/master/di.go#L601

**Comment by dtitov** [comment]
Also, please, use [discussion](https://github.com/goioc/di/discussions) for questions :)

**Comment by dtitov** [comment]
Closing this issue for now. Feel free to use discussions if you have any other questions.
