### ISSUE TITLE
Fail to inject dependencies

### ISSUE THREAD

**Issue by Dudesons** [goioc/di#21]
Hi @dtitov ,
I'm trying to use your package but I have an issue on the initialize part no one of my dependency are injected.
I think misunderstand something but I don't find the issue maybe you can explain me what I miss.

I'm trying to do:
```
                     |---> RepoA -|
db client ---> |---> RepoB -| ----> ServiceA
                     |---> RepoC -|

```

I'm creating a db client and injecting it in different repo (responsible of the data) and then these repo will be injecting in one or many services (responsible of the business logic)

I share you some extract of my golang code.

Some struct when I'm trying to do DI:
```go
type UserRepository struct {
	CqlClient cql.CqlClient `di.inject:"CqlClient"`
}

type UserService struct {
	UserRepo          *repository.UserRepository          `di.inject:"UserRepository"`
	CommunicationRepo *repository.CommunicationRepository `di.inject:"CommunicationRepository"`
	AuthRepo          *repository.AuthRepository          `di.inject:"AuthRepository"`
}


```

Registration of my beans:
```go
repositories := map[string]interface{}{
	"UserRepository":          &repository.UserRepository{},
	"CommunicationRepository": &repository.CommunicationRepository{},
	"AuthRepository":          &repository.AuthRepository{},
}

 // skip code of the init of cqlClient

_, err = di.RegisterBeanInstance("CqlClient", cqlClient)
if err != nil {
	l.Fatalw(context.Background(), err.Error())
}

for k, v := range repositories {
	_, err = di.RegisterBeanInstance(k, v)
	if err != nil {
		l.Fatalw(context.Background(), err.Error())
	}
}
```

I'm calling the function `InitializeContainer`

```go
err = di.InitializeContainer()
if err != nil {
	l.Fatalw(context.Background(), err.Error())
}
defer di.Close()
```

the di.Close() is called only when my server is shutdown.

Some prints where I can see the injection is not done:
```go
fmt.Println(di.GetBeanScopes())
```

```
map[AddressService:singleton AuthRepository:singleton CommunicationRepository:singleton CqlClient:singleton UserRepository:singleton UserService:singleton]
```

```go
fmt.Println(di.GetBeanTypes())
```

```
map[AddressService:*address.AddressService AuthRepository:*repository.AuthRepository CommunicationRepository:*repository.CommunicationRepository CqlClient:*cql.CqlManager UserRepository:*repository.UserRepository UserService:*user.UserService]
```

```go
fmt.Println(di.GetInstance("CqlClient"))
```

```
&{<nil> 0xc0003ec380 0xc00011c008 [x-user-uuid x-app-platform x-app-version x-app-build x-request-id uber-trace-id] 0xc0000ae588 <nil> []}
```

```go
fmt.Println(di.GetInstance("UserRepository"))
```

```
&{<nil>}
```

```go
fmt.Println(di.GetInstance("UserService"))
```

```
&{<nil> <nil> <nil>}
```

**Comment by dtitov** [comment]
Hi @Dudesons,

Thanks for trying out the library. Right away, I see one issue with your code:
```
_, err = di.RegisterBeanInstance(k, v)
```

This is not how you should register your repos. Instead, you should register them by class, i.e.:
```
_, _ = di.RegisterBean("UserRepository", reflect.TypeOf((*repository.UserRepository)(nil)))
_, _ = di.RegisterBean("CommunicationRepository", reflect.TypeOf((*repository.CommunicationRepository)(nil)))
_, _ = di.RegisterBean("AuthRepository", reflect.TypeOf((*repository.AuthRepository)(nil)))
```

Otherwise, you are just creating empty structs and registering them as beans, so injection won't happen.

**Comment by Dudesons** [comment]
Ok, I have another question about that:
```go
_, _ = di.RegisterBean("UserRepository", reflect.TypeOf((*repository.UserRepository)(nil)))
_, _ = di.RegisterBean("CommunicationRepository", reflect.TypeOf((*repository.CommunicationRepository)(nil)))
_, _ = di.RegisterBean("AuthRepository", reflect.TypeOf((*repository.AuthRepository)(nil)))
```
I have a doubt on how can I register an instance of one my object, because when I read the README at this section: https://github.com/goioc/di#beans-registration on `Using pre-created instance`, seems to match my need but if I correctly understand you it doesn't work with the inject.

**Comment by dtitov** [comment]
By "pre-created" instance, I meant the self-sufficient instance that doesn't need any injections to it, let's say `string` or other dependency-less struct. If you need injections to be done, then you should use `RegisterBean` - and `di` will create an instance for you automatically + will inject the dependencies :)

**Comment by Dudesons** [comment]
Thanks a lot @dtitov I updated my project and now it works. :) 
The thing I didn't understand / miss in the doc is the fact that `di` creates an instance automatically.
Really good job for the library.

**Comment by dtitov** [comment]
I'm glad that it helped :)
