### ISSUE TITLE
postconstruct does not support dependency, postconstruct executes random 

### ISSUE THREAD

**Issue by junneyang** [goioc/di#25]

**Comment by dtitov** [comment]
Please, provide more detailed description. And also steps to reproduce the issue (code snippet).

**Comment by junneyang** [comment]
> Please, provide more detailed description. And also steps to reproduce the issue (code snippet).

1. code example:
```
package main

import (
	"fmt"
	"reflect"

	"github.com/goioc/di"
)

type A1 struct {
	Name string
}

func (a1 *A1) PostConstruct() error {
	//time.Sleep(2 * time.Second)
	a1.Name = "a1"
	return nil
}

type A2 struct {
	A1      *A1 `di.inject:""`
	Message string
}

func (a2 *A2) PostConstruct() error {
	a2.Message = "hello, " + a2.A1.Name
	fmt.Printf("a2.A1: %v, a2.Message: %v \n", a2.A1, a2.Message)
	return nil
}

func main() {
	for i := 0; i < 20; i++ {
		di.RegisterBean("A2", reflect.TypeOf((*A2)(nil)))
		di.RegisterBean("A1", reflect.TypeOf((*A1)(nil)))
		di.InitializeContainer()
		di.Close()
	}
}
```
3. test result:
```
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{a1}, a2.Message: hello, a1 
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{a1}, a2.Message: hello, a1 
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{a1}, a2.Message: hello, a1 
a2.A1: &{a1}, a2.Message: hello, a1 
a2.A1: &{a1}, a2.Message: hello, a1 
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
a2.A1: &{}, a2.Message: hello,  
```

**Comment by dtitov** [comment]
OK, I see now, thanks. The reason is that there's no defined order for calling `PostConstruct()`, it's indeed random. When the `PostConstruct()` is called for `A2` - it doesn't necessarily mean that it was already called for `A1`. 

I'm not sure if it's something to be fixed, to be honest, because most likely your real scenario can be implemented in a better way, i.e. by defining whatever you like to inject as a bean. 

But, out of curiosity, how do you see the solution for this? Would you like to have a feature that would allow ordered initialization with `PostConstruct()`?

**Comment by junneyang** [comment]
> OK, I see now, thanks. The reason is that there's no defined order for calling `PostConstruct()`, it's indeed random. When the `PostConstruct()` is called for `A2` - it doesn't necessarily mean that it was already called for `A1`.
> 
> I'm not sure if it's something to be fixed, to be honest, because most likely your real scenario can be implemented in a better way, i.e. by defining whatever you like to inject as a bean.
> 
> But, out of curiosity, how do you see the solution for this? Would you like to have a feature that would allow ordered initialization with `PostConstruct()`?

i would better to ask you a better implement on this scenario, thanks very much

**Comment by dtitov** [comment]
How about this?
```go
type A1 struct {
	Name *string `di.inject:"A1Name"`
}

type A2 struct {
	A1      *A1 `di.inject:""`
	Message string
}

func (a2 *A2) PostConstruct() error {
	a2.Message = "hello, " + *a2.A1.Name
	return nil
}

func (suite *TestSuite) Test() {
	for i := 0; i < 20; i++ {
		a1Name := "a1"
		RegisterBeanInstance("A1Name", &a1Name)
		RegisterBean("A1", reflect.TypeOf((*A1)(nil)))
		RegisterBean("A2", reflect.TypeOf((*A2)(nil)))
		InitializeContainer()
		a2 := GetInstance("A2").(*A2)
		fmt.Printf("a2.A1: %v, a2.Message: %v \n", a2.A1, a2.Message)
		Close()
	}
}
```
If you define the name for the `A1` as a `string`-bean, then the problem is solved, because now it's an explicit dependency which is guaranteed to be already set by the time you call `PostConstruct()` for `A2`.

**Comment by junneyang** [comment]
> 

thanks very much, 
looking forward to the `ordered initialization with PostConstruct` feature ~

**Comment by junneyang** [comment]
> > 
> 
> thanks very much, also looking forward to the `ordered initialization with PostConstruct` feature ~

how about this feature @dtitov

**Comment by dtitov** [comment]
Sorry, but currently I have no time for this. If you like - feel free to provide a pull request.
