### ISSUE TITLE
[Bug report] Can't get another bean instance from bean factory, despite of the docs

### ISSUE THREAD

**Issue by mih-kopylov** [goioc/di#41]
**Describe the bug**
Documentation says:

> By the way, you can even lookup other beans within the factory:

```go
di.RegisterBeanFactory("beanID", Singleton, func(context.Context) (interface{}, error) {
	return di.GetInstance("someOtherBeanID"), nil
})
```

But it fails to initialize a container.
```
panic: container is not initialized: can't lookup instances of beans yet

goroutine 1 [running]:
github.com/goioc/di.GetInstance(...)
	/tmp/gopath719623559/pkg/mod/github.com/goioc/di@v1.7.1/di.go:499
main.main.func1({0x5a0440?, 0xc000016b40?})
	/tmp/sandbox1767667263/prog.go:16 +0xc7
github.com/goioc/di.createSingletonInstances()
	/tmp/gopath719623559/pkg/mod/github.com/goioc/di@v1.7.1/di.go:414 +0x8cc
github.com/goioc/di.InitializeContainer()
	/tmp/gopath719623559/pkg/mod/github.com/goioc/di@v1.7.1/di.go:104 +0xa5
main.main()
	/tmp/sandbox1767667263/prog.go:22 +0xb1

Program exited.
```

See example:
https://go.dev/play/p/K-dlscM8hvi

```go
package main

import (
	"context"

	"github.com/goioc/di"
	"github.com/samber/lo"
)

func main() {
	bean1 := "value1"
	_ = lo.Must(di.RegisterBeanInstance("bean1", &bean1))
	_ = lo.Must(
		di.RegisterBeanFactory(
			"bean2", di.Singleton, func(ctx context.Context) (interface{}, error) {
				innerBean1 := di.GetInstance("bean1").(*string)
				bean2 := *innerBean1 + "!"
				return &bean2, nil
			},
		),
	)
	lo.Must0(di.InitializeContainer())
}
```

**Comment by dtitov** [comment]
Good catch! Indeed, looking up another bean works only if the scope for the bean factory is `Prototype`. It would fail with `Singletone` (which makes sense). I've updated the readme 👍

**Comment by mih-kopylov** [comment]
Ok, @dtitov, thanks for the information.

Is there a way to build a bean factory for a bean that has an external dependency? 

For example, there's a bean Config with credentials and other configuration, and I want to make a bean like this:

```go
type MyServiceClient struct {
    api *MyServiceApi
}
```

where `MyServiceApi` is made like this:

```go
api = NewMyServiceApi(config.Url, config.Token)
```

So I have a bean of type `Config`, and want to build a bean of type `MyServiceClient` with BeanFactory, where I need to use `Config` bean.
How to do that?

**Comment by dtitov** [comment]
I see only two options here:
1. Either don't make your config a bean - just have it as a plain Go struct (global var) and use it wherever you need.
2. Or create your `MyServiceApi` not with a bean factory, but as a regular singleton bean, and then use `PostConstruct()` to initialize it by applying your configuration from the injected singleton `Config` bean.

Unfortunately, singleton beans produced by the bean factory can't look up other beans during initialization (as you already discovered), so there's not much that can help here...

**Comment by mih-kopylov** [comment]
Yeah, I see now. That's unfortunate, I got used to using Spring's bean factories that have such an ability.

Probably, it's worth building a graph of dependencies and create some singletons first, so that other factories are able to lookup them during initialization later. Pretty much like Spring does that 🙂

**Comment by dtitov** [comment]
Yes, this is a good idea/suggestion. Unfortunately, I have very little time now to dedicated to this project, but if you like - your PR on this will be well appreciated :) For now, I'll close this issue, but feel free to reopen it if you get any new input.
