### ISSUE TITLE
[Feature request] Add examples about how to use this library

### ISSUE THREAD

**Issue by 1saifj** [goioc/di#43]
**Is your feature request related to a problem? Please describe.**
No, it is a request to add examples as code and as a markdown explaining how to use this library.

**Describe the solution you'd like**
Code examples, and design architecture suggested by the author.  

**Describe alternatives you've considered**
Without code examples, it would be difficult how to integrate this library with architectures like clean architecture for instance or how to use it in general.

**Additional context**
None.

**Comment by dtitov** [comment]
There are plenty of examples in the README: https://github.com/goioc/di/blob/master/README.md

Also, there are even more examples in the tests: https://github.com/goioc/di/blob/master/di_test.go

Also, there's a side project with web-wrapper, it has its own examples: https://github.com/goioc/web

I'm pretty sure this should be sufficient 😊
