### ISSUE TITLE
[Feature request] Autowiring  beans into slice or map depending on the interface

### ISSUE THREAD

**Issue by mikekonan** [goioc/di#8]
It would be very useful to autowire beans of the specific interface into the []Interface or map[string]Interface.

Spring Java examples:
```
@Autowired
private Map<String, Interface> services;

@Autowired
private List<Interface> services;
```

Want to have something like in go:

```
type Service struct {
     map[string]Interface services `di.mapBeans:"Interface"`
     []Interface services `di.sliceBeans:"Interface"`
}

```

**Comment by dtitov** [comment]
Good idea 👍 I'll look into it.

**Comment by mikekonan** [comment]
> Good idea 👍 I'll look into it.

What are your thoughts? Do you have time to implement it?

**Comment by dtitov** [comment]
Sorry, mate, I was in the progress of changing the job and had dramatically less time for my opensource initiatives 😅

Perhaps it's something that could be interesting for @marniks7? 

And, of course, you are more than welcome to make PRs of your own ☺️

**Comment by dtitov** [comment]
P.S. I did look into this and I see no problems with adding this functionality, it just needs time to be done :)

**Comment by dtitov** [comment]
@mikekonan, I'm happy to announce that it's been finally implemented :) 

Check out the examples:

```go
type SingletonBean struct {
	someOtherBeans []*string `di.inject:""`
}
```
```go
type SingletonBean struct {
	someOtherBeans map[string]*string `di.inject:""`
}
```
```go
type SingletonBean struct {
	someOtherBeans []io.Reader `di.inject:""`
}
```
```go
type SingletonBean struct {
	someOtherBeans map[string]io.Reader `di.inject:""`
}
```

**Comment by mikekonan** [comment]
Amazing, thanks a lot!
