### ISSUE TITLE
[Feature request] Bean lifecycle

### ISSUE THREAD

**Issue by mikekonan** [goioc/di#9]
We rely on bean lifecycle methods and need to have at least `bean.destroy()` and `container.shutdown()` methods.

Spring lifecycle is following:
![image](https://user-images.githubusercontent.com/36304777/98658717-6abe1800-2354-11eb-8eef-bffb76031623.png)

Actually, I'm not sure that we need to implement all of these hooks but I believe `bean.destroy()` and `container.shutdown()` are really necessary.

**Comment by dtitov** [comment]
Can you describe any particular use-case of bean destruction? I've been using Spring for quite some time and I have never had a need to destroy a bean (neither did I ever need to completely shut down the container) 🤔

**Comment by mikekonan** [comment]
It needed for implementing graceful shutdowns when your service destroys beans depending on the dependency graph.
